# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/graphai
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: packages/graphai
        cache: 'npm'
    - run: yarn install
    - run: npx ts-node -r tsconfig-paths/register  samples/express/server.ts &
    - run: cd tests/http-server/docs/ && npx http-server &
    - run: yarn test
    - run: yarn http_test
    - run: yarn run eslint
